### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Gwiz65** [jech/dht#10]
Bug: struct bucket.time is defined as int - should be time_t

**Comment by Gwiz65** [comment]
Oops. It's send_find_node & send_get_node that are not appearing to work correctly. They get passed -1 for want. Debugf output shows them sending IPv4 addresses (I haven't confirmed if they are actually sent or not) but they never, ever send IPv6 address.

**Comment by Gwiz65** [comment]
One of these days I will learn to type. :) 

Meant "send_get_peers" not "send_get_node".

**Comment by jech** [comment]
Fixed in commit e10b80e0736d64c0a00870d1d18d1bf08c20d590.
