### ISSUE TITLE
free(buckets6)

### ISSUE THREAD

**Issue by cfpp2p** [jech/dht#11]
dht.c 1668

    if(s >= 0) {
        buckets = calloc(sizeof(struct bucket), 1);
        if(buckets == NULL)
            return -1;
        buckets->af = AF_INET;

        rc = set_nonblocking(s, 1);
        if(rc < 0)
            goto fail;
    }

    if(s6 >= 0) {
        buckets6 = calloc(sizeof(struct bucket), 1);
        if(buckets6 == NULL)
            return -1;
        buckets6->af = AF_INET6;

        rc = set_nonblocking(s6, 1);
        if(rc < 0)
            goto fail;
    }

...

     fail:
        free(buckets);
        buckets = NULL;
        free(buckets6);
        buckets6 = NULL;
        return -1;

what happens if ***set_nonblocking(s, 1)*** returned an error
before we might ***buckets6 = calloc*** (which comes after)
***fail:*** free(buckets6) ?

Or maybe the opposite
no v4 socket at all and ***set_nonblocking(s6, 1)*** returns error
***fail:*** free(buckets) ?

maybe I'm not seeing this right...

**Comment by jech** [comment]
The we call `free(NULL)`, which does nothing.

**Comment by cfpp2p** [comment]
@jech 
I use your well designed DHT library for transmission bittorrent.
Thank you.
In regards to free(), and  pertaining to libtransmission,
you've coded only tr_free() within tr-dht.c .

I understand that your DHT library is expected to be compiled
with a standards complying compiler, apparently libtransmission might
not be.

For conformity tr-dht.c strictly utilizes libtransmission
utils.h wrapper tr_free().
https://trac.transmissionbt.com/ticket/7#comment:48

> changes to tr-dht:
use tr_new(), **tr_free()** instead of malloc(), free() 

**utils.h**
> /** @ brief  Portability wrapper around free () in which `NULL' is a safe argument */
void tr_free (void * p);

**utils.c**
>     void
    tr_free (void * p)
    {
      if (p != NULL)
        free (p);
    }

I do thank you for all of the support you have provided to the transmission project.

refs.

C99 Standard

    7.20.3.2 The free function
    
    Synopsis
    
    [#1]
    
    #include <stdlib.h>
    void free(void *ptr);
    
    Description
    
    [#2] The free function causes the space pointed to by ptr to
    be deallocated, that is, made available for further
    allocation. If ptr is a null pointer, no action occurs.
    Otherwise, if the argument does not match a pointer earlier
    returned by the calloc, malloc, or realloc function, or if
    the space has been deallocated by a call to free or realloc,
    the behavior is undefined.
    
    Returns
    
    [#3] The free function returns no value.


[remove redundant NULL check before free()](https://www.winehq.org/pipermail/wine-patches/2006-October/031544.html)

**Comment by cfpp2p** [comment]
-------- Original Message --------
Subject: Re: [dht] free(buckets6) (#11)

**Comment by jech** [comment]
Yes, there used to be standard libraries (not compilers — the free function is in the standard library) that didn't deal with the `free(NULL)` case.  I haven't seen one of those since the early 1990s.
