### ISSUE TITLE
Implement support for BEP-14 Local Service Discovery

### ISSUE THREAD

**Issue by ppetr** [jech/dht#21]
[BEP-14](http://www.bittorrent.org/beps/bep_0014.html) adds support for local peer discovery, which seems to be a nice complement for speeding up both searches and peer discovery.

**Comment by jech** [comment]
That doesn't belong in this library, which implements the DHT.  LSD should be implemented in the BitTorrent client or in a different library.

Note that LSD has some serious privacy implications — it broadcasts every swarm you belong to on the local net.  Do you really want your flatmates to know what kind of naked people you like looking at?

**Comment by ppetr** [comment]
Thank you for the explanation. My idea was that DHT would use LSD without infohashes, just to locate possible local peers. This shouldn't leak any information about swarms.

Regarding security, is LSD with exposing infohashes any worse than if somebody on the local network in the  promiscuous mode and listens on the DHT traffic?

**Comment by jech** [comment]
> Regarding security, is LSD with exposing infohashes any worse than if somebody
> on the local network in the promiscuous mode and listens on the DHT traffic?

DHT traffic is sent over unicast, so a switch will usually prevent the
traffic from reaching nodes other than your Internet gateway.  Granted,
you can overflow the switches learning tables to get it to flood the
traffic, but with LSD it's just too easy.
