### ISSUE TITLE
making libdht

### ISSUE THREAD

**Issue by nschloe** [jech/dht#22]
I came across this working on the Debian integration of [transmission](https://github.com/transmission/transmission). There's the option of using a system DHT library instead of bundling it, but if I see correctly, dht can't build as a library yet. I don't know why not, given that dht is so useful.

I could create a PR that add that, if you'd like.

**Comment by jech** [comment]
No, please link statically with libdht.  There are no ABI guarantees for `libdht`, it is meant to be linked statically.

**Comment by nschloe** [comment]
Instead of "link statically", I guess you mean bundle. Building a static library and actually linking that be would be far more superior to this approach IMO, and ABI changes could be handled by version bumps. Anyways, closing since there's no interest in this on your side.
