### ISSUE TITLE
Send a version string even if the client does not provide one

### ISSUE THREAD

**Issue by ssiloti** [jech/dht#25]
[BEP 5](http://bittorrent.org/beps/bep_0005.html) has been updated to document the long standing de-facto standard of including a version string in RPC messages. This is an important feature for identifying implementations which may be lacking features or misbehaving. The relevant section of BEP5:

> A key `v` should be included in every message with a client version string. The string should be a two character client identifier registered in [BEP 20](http://www.bittorrent.org/beps/bep_0020.html) followed by a two character version identifier.

By convention the version string identifies the DHT implementation rather than the client application. Thus this library should have it's own client identifier which it uses to populate the version string. Ideally it would always use this string regardless of what the client application's identifier is.

**Comment by jech** [comment]
No, sorry.  The client is the boss.
