### ISSUE TITLE
API improvements around DHT_EVENT_SEARCH_DONE notification

### ISSUE THREAD

**Issue by ghazel** [jech/dht#26]
Tracking when a search completes is somewhat difficult at the moment. If the user allocates memory for a search, calls `dht_search()`, and then deallocates when `DHT_EVENT_SEARCH_DONE` arrives, memory can leak. The user can try to keep track of in-progress searches, and also its own timeout values, but this is is extra effort and slightly inaccurate.

There are a few small things I think could be improved about the API which should be backwards compatible:

 - if `dht_search` finds an existing `struct search`, it could return a different value (`2`?) so the caller knows not to expect an additional `DHT_EVENT_SEARCH_DONE` event
 - when a `struct search` expires, callback with `DHT_EVENT_SEARCH_DONE(6)` before freeing

I'd be happy to submit a pull request if these are welcome changes.

**Comment by jech** [comment]
> if dht_search finds an existing struct search, it could return a different value (2?)

Why not simply return -1 with errno EEXIST?

> I'd be happy to submit a pull request if these are welcome changes.

Please.  I've got some minor API changes pending, so this is a good time.

**Comment by ghazel** [comment]
It's not quite an error if `dht_search` finds an existing `struct search`. It resets some fields (including the timeout) and continues the search. I'll keep that behavior and return -1/EEXIST, but it feels a little strange to me to return an error when the function did have an effect.

**Comment by jech** [comment]
> It's not quite an error if dht_search finds an existing struct search. It
> resets some fields (including the timeout) and continues the search. I'll keep
> that behavior and return -1/EEXIST, but it feels a little strange to me to
> return an error when the function did have an effect.

Perhaps you're right.  Your intuition is probably at least as good as
mine, so please implement whatever feels right to you.

-- Juliusz
