### ISSUE TITLE
"implied_port" is improperly handled

### ISSUE THREAD

**Issue by carlreinke** [jech/dht#29]
If a message includes the "implied_port" argument, the [message parser](https://github.com/transmission/dht/blob/783e5ddbc48580d4c62d30c17abfbb4a37fb8121/dht.c#L2928) finds the "port" portion of the "implied_port" argument key and uses its value as the port, which is always 0 or 1.

See [BEP 5](http://bittorrent.org/beps/bep_0005.html) for proper handling of the "implied_port" argument.

**Comment by ghazel** [comment]
Aha, thank you https://github.com/clostra/dcdn/blob/master/client.c#L222

**Comment by jech** [comment]
Fixed in d158fa7ca0cb959c6e83b53f3837622ce3541fc2.  Thanks.

**Comment by cfpp2p** [comment]
Tested https://github.com/jech/dht/commit/5853ed1e2c9c615a52f3baaf22eeb2f24f99cda8 with transmission. No problems. Thousands of `implied_port`, every last one `Both port and implied_port.`

```

            if(implied_port != 0) {
                if(port != 0) {
                    debugf("Both port and implied_port.\n");
                    /* But continue, that's what the spec says. */
                }
                switch(from->sa_family) {
                case AF_INET:
                    port = htons(((struct sockaddr_in*)from)->sin_port);
                    debugf("Announce_peer: AF_INET implied_port %d.\n", port);
                    break;
                case AF_INET6:
                    port = htons(((struct sockaddr_in6*)from)->sin6_port);
                    debugf("Announce_peer: AF_INET6 implied_port %d.\n", port);
                    break;
                default:
                    port = 0;
                    debugf("Announce_peer: unsupported sa_family! implied port set zero.\n");
                    break;
                }
            }

```

**Comment by cfpp2p** [comment]
OK, it seems to be about 25 per thousand `implied_port` that don't have `Both port and implied_port`.

**Comment by jech** [comment]
> Tested 5853ed1 with transmission. No problems.

Thanks for the feedback.

> Thousands of implied_port, every last one Both port and implied_port.

Do you recommend removing the debug statement?

-- Juliusz

**Comment by cfpp2p** [comment]
I think it might make sense to log the inverse. Does this make sense?

```

            if(implied_port != 0) {
                if(port == 0) {
                    debugf("implied_port alone.\n");
                }
                /* Continue either way, that's what the spec says. */

```

**Comment by jech** [comment]
> I think it might make sense to log the inverse. Does this make sense?

No, I don't think so.  IMHO, port and implied_port should be exclusive.

**Comment by cfpp2p** [comment]
OK, recommend removing the debug statement. It's not about debugging the DHT.

**Comment by cfpp2p** [comment]
@ghazel

> Aha, thank you https://github.com/clostra/dcdn/blob/master/client.c#L222

**0.24** implementation and DHT pollution.

https://github.com/cfpp2p/dht-trs-trs/tree/port-logging logged:

Forty-two percent of 118,152 messages contained optional `implied_port`.

Of those, 98 percent contain both
non zero `port` _**and**_ flagged (non zero) `implied_port`.
Twenty-four percent of those,
derived (implied) port value differed from `port` value.
With 0.24
twenty-four percent would have announce peer port incorrect,
NOT based on derived port, but on `port`.

With 0.24
remaining two percent
messages containing optional `implied_port`,
those with `port`=0 (or missing) **and** `implied_port` flagged on,
would then announce peer port **_1_**.

Of course this is assuming that `port` precedes `implied_port` in the message, which I didn't check.

**Comment by ghazel** [comment]
Bencoding has lexigraphically sorted keys, so `implied_port` should come first.

**Comment by jech** [comment]
> Bencoding has lexigraphically sorted keys, so implied_port should come first.

And therefore implied_port was taking priority, since memmem stops at the
first match.  Exactly the wrong behaviour.

I'm feeling pretty bad about this bug.  I'm seriously considering
switching to a proper bencoding parser, but I want dht.c to remain
a single-file implementation with minimal dependencies.

**Comment by ghazel** [comment]
Sounds like a fun challenge. How many lines would be acceptable?

**Comment by jech** [comment]
> Sounds like a fun challenge. How many lines would be acceptable?

If I give you a figure, will you cheat by using 500-character lines?

Seriously, though, size is not really a concern, simplicity is, as well as
the fact that it remains a single file with all privates hidden behind
static.

Note by the way that you shouldn't be doing any memory allocations (except
strings) or recursion -- you just need to walk the two (if memory serves)
dictionaries used by the DHT, and fill in a fixed-format struct.

**Comment by ghazel** [comment]
How about net 8 lines? https://github.com/jech/dht/pull/31
