### ISSUE TITLE
Include client version string in messages

### ISSUE THREAD

**Issue by carlreinke** [jech/dht#30]
Messages should include a "v" key with a 4-byte identifier value that contains the DHT node's 2-byte client identifier and 2-byte version identifier.  This helps immensely in tracking down bugs in other DHT implementations, as you can get an idea of which implementation you are or aren't looking for.

See [BEP 5](http://bittorrent.org/beps/bep_0005.html) for details about the client version string.

**Comment by jech** [comment]
You need to pass the value in the `v` parameter to the `dht_init` function.
