### ISSUE TITLE
Redundant check introduced in 71d4372

### ISSUE THREAD

**Issue by joel-su** [jech/dht#47]
The `if(oldest->done)` check that was added in recent commit 71d4372e66cec1caaf14c3de7dd373332bc4eab9 appears to be redundant, as `oldest->done` is necessarily set. The loop at the beginning of the function ensures it:

```
    sr = searches;
    while(sr) {
        if(sr->done &&
           (oldest == NULL || oldest->step_time > sr->step_time))
            oldest = sr;
        sr = sr->next;
    }
```

However, this changes does make the point that it's fine for the `new_search` function to return a "done" slot. But isn't it supposed to be taken care of earlier in the function by the following lines ?

```
    /* The oldest slot is expired. */
    if(oldest && oldest->step_time < now.tv_sec - DHT_SEARCH_EXPIRE_TIME)
        return oldest;
```

Or maybe I'm wrong because we consider it's fine to return a "done" search that's not yet expired ? If that's the case, it seems that the observation I was making in PR #45 was incorrect and, we could revert the code back to before this change.

Also, you seem to have forgotten the possibility that `oldest` is NULL at that point in the function. It would be the case if no search is currently marked as "done".

**Comment by jech** [comment]
Fixed in 6b63fd8ce7644cf320b62ae74efe0c0febdd3157.
