### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by naturalpolice** [jech/dht#48]
I've been monitoring activity on this project for a while and many pull requests and issues have been left unanswered for a while.

For people looking for a more complete implementation of a DHT node written in C with support for BEP-42 and BEP-44, I am the author of [naturalpolice/libdht](https://github.com/naturalpolice/libdht). I invite you to take a look.

**Comment by jech** [comment]
It has all of the required features, and there are no reported security issues.  I still haven't seen a convincing argument that BEP-42 actually increases security.  As to BEP-44, I refuse to implement it, you're not allowed to store arbitrary data in my node.
